name: the_void_protocol
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  animated_text_kit: ^4.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  google_fonts: ^8.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.11.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0

flutter:
  uses-material-design: true
